kubernetes-sigs/lws

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CLEANUP.md, .github/ISSUE_TEMPLATE/ENHANCEMENT.md, .github/ISSUE_TEMPLATE/SUPPORT.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml
fix https://github.com/kubernetes-sigs/lws/issues/5
Also Add the Issue/PR templates. This is mostly inspired by kueue.
=> Add dependabot

Makefile
/kind feature
Fixes #
Will add presubmit to test-infra as well.
```release-note
Run `make test-integration` to run integration tests locally.
```
=> Add integration test

OWNERS
/assign @ahg-g 
Fixes #
```release-note
None
```
=> nominate kerthcet as approver

README.md
=> Add documentation part-1

README.md
=> Update readme expression

pkg/controller/controller_test.go, pkg/utils/accelerators/tpu.go, pkg/utils/accelerators/tpu_test.go, pkg/utils/statefulset/statefulset_utils.go, pkg/utils/statefulset/statefulset_utils_test.go, pkg/webhook/webhook_utils_test.go, test/testutils/wrappers.go
To add unit tests to the codebase
Fixes #
```release-note
```
=> added unit tests for controller utils, tpu, and webhook utils

OWNERS
=> Add rupliu as reviewer

config/certmanager/certificate.yaml, config/default/kustomization.yaml, config/default/webhookcainjection_patch.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/leaderworkerset_editor_role.yaml, config/rbac/leaderworkerset_viewer_role.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/samples/leaderworkerset_exclusiveplacement.yaml, config/samples/leaderworkerset_multi_template.yaml, config/samples/leaderworkerset_tpu.yaml, config/samples/leaderworkerset_v1_leaderworkerset.yaml, config/webhook/service.yaml, pkg/cert/cert.go, pkg/controllers/leaderworkerset_controller.go
/kind cleanup
Fixes #56 
```release-note
```
=> Replace leader-worker-set to lws

README.md, docs/setup/install.md
Fixes #47 
```release-note
```
=> Add installation guide

go.mod
/kind cleanup
Fixes #
```release-note
```
=> Migrate go version

test/e2e/suite_test.go
=> Remove vestigial Getwd()

docs/example/saxml/README.md, docs/example/saxml/configmap.yaml
=> SaxML ConfigMap doesn't need to specify the model field

test/e2e/suite_test.go
/kind bug
```release-note
NONE
```
=> E2E test now waits for webhook to complete setup

pkg/controllers/leaderworkerset_controller.go, pkg/controllers/pod_controller.go, pkg/webhooks/leaderworkerset_webhook.go
/kind cleanup
fix some typo or comment error
Fixes #
None
```release-note
None
```
=> Fix comment error or typo

pkg/utils/pod/pod_utils_test.go
/kind cleanup
TestContainerRestarted method typo 
Fixes #
```release-note
```
=> TestContainerRestarted method typo 

Makefile
/kind cleanup
/assign @liurupeng 
Keep the same as integration test.
Fixes #
```release-note
None
```
=> remove generate from test-e2e

docs/example/saxml/README.md
Fixes #
If model attribute isn't set, model will default to the last element of the modelpath all in lowercase. So in the example, the correct model to pass for the API call is lmcloudspmd175b32test.
```release-note
```
=> Fixed Saxml deployment documentation after ConfigMap change. 

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/webhooks/leaderworkerset_webhook.go
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/15
```release-note
None
```
=> Use kubebuilder tag instead of webhook

test/e2e/e2e_test.go, test/integration/webhooks/pod_test.go, test/testutils/util.go, test/testutils/validators.go
Added E2E tests around some common use cases
```release-note
NONE
```
=> More E2E tests and general cleanup

README.md
Link to examples in readme for general usage questions.
Fixes #92 
```release-note
NONE
```
=> add examples link in readme

cmd/main.go
refer to: https://github.com/kubernetes-sigs/lws/issues/94
Fixes #
None
```release-note
None
```
=> feat: add kubeconfig value

pkg/webhooks/leaderworkerset_webhook_test.go
=> Adding unit tests for leaderworkerset_webhook

docs/setup/install.md
=> Update lws version for installation

go.mod, go.sum
=> Downgrading controller-runtime to 0.16.3

kep/NNNN-Template/README.md
Add KEP template following JobSet's structure
Fixes #
```release-note
```
=> add kep template

README.md
Fixes wrong example url in README.md
=> fix example url in README.md

Makefile, hack/update-toc.sh, hack/verify-toc.sh, keps/NNNN-Template/README.md, keps/NNNN-Template/kep.yaml
/kind cleanup
Fixes #
Also update with the latest KEP template.
```release-note
None
```
=> Add KEP template update/verify tool

keps/135-startup-policy/README.md, keps/135-startup-policy/kep.yaml
ref: #135 
Fixes #
```release-note
```
=> kep-135 add startup policy api

config/default/manager_auth_proxy_patch.yaml
This PR removes the resource limit for auth proxy since we saw OOM issue in prod use case
Fixes #
```release-note
```
=> Remove resource limit for auth proxy

api/leaderworkerset/v1/leaderworkerset_types.go, pkg/controllers/leaderworkerset_controller.go, pkg/controllers/leaderworkerset_controller_test.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/validators.go
/kind feature
Fixes #106
```release-note
```
=> Adding Upgrade in Progress Condition

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/webhooks/pod_webhook.go
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/147
```release-note
```
=> Chore: convert required fields to optional

Makefile
/kind feature
- update e2e k8s version to v1.30.0
more detail  https://github.com/kubernetes-sigs/lws/pull/140
```release-note
```
=> chore: update e2e k8s version to v1.30.0

docs/setup/install.md
=> Update the lws version of the installation guide

Makefile, Makefile-deps.mk, docs/reference/leaderworkerset.v1.md, hack/genref/config.yaml, hack/genref/markdown/members.tpl, hack/genref/markdown/pkg.tpl, hack/genref/markdown/type.tpl
Create API reference doc to easily reference LWS API fields
Fixes #169 
```
make generate-apiref
```
NONE
=> docs: add LeaderWorkerSet API reference

client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go, config/rbac/role.yaml, pkg/controllers/leaderworkerset_controller.go
/kind bug
Openshift is unable to patch statefulset finalizers. Not entirely sure why this occurs on openshift and not elsewhere. 
Fixes #172 
```release-note
Add explicit rbac for statefulset/finalizers update.
```
=> statefulset finalizer rbac update

client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go, hack/update-codegen.sh
/kind bug
Fixes https://github.com/kubernetes-sigs/lws/issues/195
```release-note
None
```
=> fix make generate

docs/examples/llamacpp/k8s/lws.yaml, docs/examples/llamacpp/tools/llamacpp-leader/cmd/llamacpp-leader/main.go
/kind cleanup
'leaderworkerset.sigs.k8s.io/size' can be obtained via LWS_GROUP_SIZE
Fixes #
```release-note
NONE
```
=> simply llama.cpp example

docs/setup/install.md
=> Update installation guide 

cmd/main.go, config/default/manager_auth_proxy_patch.yaml, docs/setup/install.md, pkg/cert/cert.go
/kind feature
Fixes https://github.com/kubernetes-sigs/lws/issues/215
```release-note
Add support to install leaderWorkerSet controller at an arbitrary namespace
```
=> Add support to install lws at an arbitrary namespace

Makefile
/kind feature
When I use `make docker-buildx`, I found some error because build args(BASE_IMAGE, BUILDER_IMAGE) are not passed to dockerfile. So I add build-arg to docker buildx.
Fixes #
```release-note
NONE
```
=> feat: add build arg to docker buildx

hack/cherry_pick_pull.sh
This PR adds a script for cherry pick, from https://github.com/kubernetes/kubernetes/blob/e8b59afec65762ec33c683f376d5a1e5959476c2/hack/cherry_pick_pull.sh#L22
Fixes #
np
NP
```release-note
```
=> Add cherry-pick script

config/default/manager_auth_proxy_patch.yaml
/kind bug
Changes verbosity level to 2 to view non error logs
Fixes #237 
```release-note
```
=> Changed log level to 2

config/rbac/role.yaml, pkg/controllers/pod_controller.go
/kind bug
If you install LWS on openshift, you will get 
```
2024-11-07T16:55:50Z	ERROR	Reconciler error	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"leaderworkerset-sample-1","namespace":"lws-test"}, "namespace": "lws-test", "name": "leaderworkerset-sample-1", "reconcileID": "50ddfa5f-8eb8-4e00-8d7c-3c0c07fb7db7", "error": "statefulsets.apps \"leaderworkerset-sample-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```
We need both statefulset and pods finalizers rbac to allow for LWS to run on openshift.
Fixes #172 
```release-note
Add finalizer roles to manager role to allow for running on openshift
```
=> add pods finalizer update rbac to allow lws to run in openshift

docs/setup/install.md
Add a doc to explain how to install to a different namespace
Fixes #
```release-note
NONE
```
=> add doc to say how to install in a different namespace

docs/reference/leaderworkerset.v1.md
Updates the reference doc to include new fields such as `NetworkConfig` and update `RestartPolicy`
```release-note
```
=> Update Reference Doc

OWNERS
=> Updating owners

charts/lws/README.md
=> Replaced Kueue with LWS on chart/lws ReadMe

pkg/controllers/leaderworkerset_controller.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go
/kind bug
It fixes a flaky test, needed to unblock future PRs. 
Fixes #
```release-note
```
=> Fixed flaky ControllerRevision test and add CR events

cmd/main.go, config/default/kustomization.yaml, config/default/manager_config_patch.yaml, config/default/manager_metrics_service.yaml, test/e2e/e2e_test.go
/kind bug
Addressed open comments left in #284 
Fixes #
```release-note
```
=> Fixed metrics service port, added log level flag back

docs/examples/vllm/build/Dockerfile.TPU
=> Add public vLLM on TPU image

api/leaderworkerset/scheme/scheme.go, api/leaderworkerset/v1/groupversion_info.go
Removes the dependency to controller-runtime from the v1 package
Fixes #283
```release-note
```
=> Removed dependency to controller-runtime from v1 package

.github/ISSUE_TEMPLATE/new-release.md
=> Add wg-serving to newsletters in release template

charts/lws/README.md, charts/lws/values.yaml
/kind cleanup
As part of https://github.com/kubernetes-sigs/lws/issues/274, need to remove the readme and values.yaml from the helm charts
Follow by https://github.com/kubernetes-sigs/lws/pull/308
Fixes #274
```release-note
Removed kube-rbac-proxy from helm charts
```
=> Removed kube-rbac-proxy from helm charts readme and values.yaml

Dockerfile, Makefile
Reverts kubernetes-sigs/lws#321 due to https://github.com/kubernetes-sigs/lws/issues/328#issuecomment-2597082466
=> Revert "Make lws image multi-platform"

charts/lws/templates/rbac/clusterrole.yaml, config/rbac/role.yaml
/kind feature
Remove pods create permission since it's sensitive and unnecessary.
Fixes #320
```release-note
```
=> Remove pods create permission

Dockerfile
/kind cleanup
Copy the files with general copy rather than adding them into Dockerfile.
Fixes #
https://github.com/kubernetes-sigs/lws/pull/325#issuecomment-2596927125
We hit this quite a bit in JobSet repo and it is always a source of confusion.
I don't see why we need to make this more complicated than it needs to be.
```release-note
NONE
```
=> copy the golang code rather than add folders into docker file

charts/lws/templates/webhook/webhook.yaml, config/webhook/manifests.yaml, pkg/webhooks/pod_webhook.go
/kind bug
Removes the update operation from the pod webhook as it is not needed, and can cause issues with the garbage collector.
Fixes #346 
```release-note
```
=> Removed update operation from pod webhook

charts/lws/templates/webhook/webhook.yaml, config/webhook/manifests.yaml, pkg/controllers/pod_controller.go, pkg/webhooks/pod_webhook.go
=> Patches for 0.5.1 release

charts/lws/Chart.yaml, docs/setup/install.md
Part of #351 
```release-note
```
=> updating version in docs

charts/lws/Chart.yaml, docs/setup/install.md
Updates docs for v0.5.1 release
```release-note
```
=> Updating docs on main branch

pkg/controllers/pod_controller.go
Fixes #https://github.com/kubernetes-sigs/lws/issues/359
=> Fix for odd numbers of arguments passed as key-value pairs for logging issue

config/crd/kustomization.yaml
/kind cleanup
The comments were redundant as they had appeared earlier, so they have been removed.
Fixes #
```release-note
Fix redundant comments in `config/crd/kustomization.yaml`
```
=> Fix redundant comments in `config/crd/kustomization.yaml`

docs/examples/tensorrt-llm/README.md, docs/examples/tensorrt-llm/build/Dockerfile, docs/examples/tensorrt-llm/build/install_model.sh, docs/examples/tensorrt-llm/build/server.py, docs/examples/tensorrt-llm/lws.yaml, docs/examples/tensorrt-llm/rbac.yaml, docs/examples/tensorrt-llm/service.yaml
Adds user guide to for multihost inference using TensorRT-LLM
Fixes #231
```release-note
```
=> Adding User Guide for TensorRT-LLM 

docs/setup/install.md
xref: https://github.com/kubernetes-sigs/lws/issues/315
```release-note
None
```
=> Add feature gate introduction for MaxUnavailableStatefulSet

README.md, docs/showcase.md
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/324
```release-note
None
```
=> Add adopters, integrations, talks

docs/showcase.md
This pattern demonstrates an Amazon EKS Cluster with an EFA-enabled nodegroup that support multi-node inference using vLLM, and lws (LeaderWorkerSet). This gets you close to a near production grade setup.
Fixes #
```release-note
NONE
```
=> doc: Add terraform based EKS Blueprints pattern for multi-node inference

README.md
/kind cleanup
Introduced by https://github.com/kubernetes-sigs/lws/pull/380
```release-note
None
```
=> Fix the error link of adopter page

docs/examples/sglang/README.md, docs/examples/sglang/lws.yaml
Adds user guide to for multi-host inference using SGLang
Fixes #371
```release-note
Adds user guide to for multi-host inference using SGLang
```
=> Adding User Guide for SGLang

docs/examples/vllm/build/ray_init.sh
allows for example `--dashboard-host=0.0.0.0` to be passed through to `ray start` 
/kind cleanup
Fixes #
```release-note
NONE
```
=> Allow pass through of additional params to "ray start" in ray_init.sh

pkg/controllers/pod_controller.go
/kind bug
When running on Kubernetes clusters <1.27 without the StatefulSetStartOrdinal feature gate enabled, LeaderWorkerSet controllers enter infinite reconciliation loops that exhaust cluster resources.
So the PR is to block infinite reconciliation loops caused by missing Kubernetes version checks when StatefulSetStartOrdinal isn't enabled (clusters <1.27).
Fixes #391
Fixes #385
Fixes #390
```release-note
Fix infinite StatefulSet creation loops by validate leader annotations
```
=> Fix infinite StatefulSet creation loops by validate leader annotations

.github/ISSUE_TEMPLATE/new-release.md, Makefile, charts/lws/README.md, charts/lws/values.yaml, cloudbuild.yaml, config/manager/kustomization.yaml, hack/e2e-test.sh
/kind cleanup
Migrate off of GCR as part of k8s-infra work.
Fixes #397 
```release-note
NONE
```
=> use staging images instead of gcr

docs/setup/install.md
/kind cleanup
We got several feedbacks about version lower than v1.26 and lws behaves unexpected. Let's emphasize the version requirement in installation documentation.
Fixes #
```release-note
None
```
=> Emphasize the version requirement

Makefile
/kind bug
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-lws-push-images/1899147188785647616 current image push fails due to `yq` not in directory. Added dependencies to match JobSet 
Fixes #
```release-note
```
=> Adding dependencies for push-chart.sh to Makefile

cloudbuild.yaml
/kind cleanup
Fix toolchain error and bump step name to later version
Fixes #
```release-note
NONE
```
=> fix image build toolchain errors

README.md, site/content/en/docs/concepts/_index.md
Changes the LWS diagram to use the new logo
Fixes #
```release-note
```
=> updating diagrams to include new logo

README.md, site/content/en/_index.html
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/372
```release-note
None
```
=> Update README.md to include the logo and website

hack/e2e-test.sh
/kind cleanup
While investigating https://github.com/kubernetes-sigs/lws/issues/437, I realized that there is almost no logs making the troubleshooting easier (e.g. https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_lws/445/pull-lws-test-e2e-main-1-31/1902041411415445504/artifacts/). 
This PR exporting kind and cluster related logs under artifacts directory to troubleshoot any issues including the flaky one that I'm looking right now.
This PR mimics from jobset https://github.com/kubernetes-sigs/jobset/blob/15adf20ce9e0a10f01e7bcd8ea585a011814a2aa/hack/e2e-test.sh#L14-L17
```release-note
None
```
=> Export kind and cluster related logs under artifacts directory for e2e

Dockerfile, docs/examples/llamacpp/tools/blobserver/go.mod, docs/examples/llamacpp/tools/clichat/go.mod, docs/examples/llamacpp/tools/llamacpp-leader/go.mod, go.mod
/kind cleanup
Upgrade golang to 1.24.
Fixes #449
```release-note
Upgrade golang to 1.24.
```
=> update to golang 1.24

site/content/en/_index.html
/kind bug
After the changes introduced in #446, it causes a visual bug
This is how it looks like after the fix
Fixes #
```release-note
```
=> Fix website layout

charts/lws/templates/rbac/clusterrole.yaml
/kind bug
Fixes #
fixed https://github.com/kubernetes-sigs/lws/issues/454
I'm not sure if directly cherry-picking is appropriate
I'm new to LWS, so I'll try submitting a PR first and see how it goes.
```release-note
```
=> Cherrypick 319 to release-0.5

OWNERS
/kind flake
Hello 👋, I'm interested in becoming a reviewer for LWS. Having contributed several PRs, I'm eager to assist with reviews and further my involvement.
=> Add Yankay(myself) as reviewer

.github/dependabot.yml
/kind cleanup
Adds dependabot for npm packages that the site uses. Matches what Kueue does https://github.com/kubernetes-sigs/kueue/blob/main/.github/dependabot.yml
Fixes #
```release-note
```
=> Adding dependabot for npm packages

site/content/en/docs/troubleshooting/_index.md
Add troubleshooting page, for the issue:
- #390
- #430
- #410
Fixes #448
Fixes #410
```release-note
Add troubleshooting page in site
```
=> [Doc] Add troubleshooting page in site

netlify.toml
/kind cleanup
Because Node.JS 16 is endoflife : https://endoflife.date/nodejs , and https://github.com/kubernetes-sigs/lws/pull/465 needs node.js >= 18 .
Remove node.js version in `netlify.toml` for the site. So it can be automatically up to date by netlify.
Fixes #
```release-note
Remove node.js version in `netlify.toml` for the site.
```
=> Remove node.js version in `netlify.toml` for site

OWNERS
I've involved in many PRs https://github.com/kubernetes-sigs/lws/pulls?q=is%3Apr+ardaguclu+is%3Aclosed for a while and I'm planning to continue contributing to the code base and maintaining it.
This PR adds me (aka. ardaguclu) into the reviewers list, if you also support this.
```release-note
None
```
=> Add ardaguclu in reviewers

README.md, site/content/en/docs/overview/_index.md
Fixing the image URL typo in README.md.
Fixes #
```release-note
docs: fix image url typo in README.md
```
=> docs: fix image url typo in README.md

charts/lws/Chart.yaml, site/config.toml, site/content/en/docs/installation/_index.md
part of https://github.com/kubernetes-sigs/lws/issues/470
```release-note
```
=> Release v0.6.0

Makefile, charts/lws/values.yaml, hack/push-chart.sh
/kind bug
The `image.repository` is not used in helm chart but the `image.manager.repository`. waiting for confirmation.
Fixes #
```release-note
```
=> Fix helm update

cloudbuild.yaml
/kind bug
image postsubmit fails due to a timeout.
LWS builds 4 platforms so maybe we need a beefy machine.
Kueue used this already on their builds.
Fixes #436 
https://github.com/kubernetes-sigs/kueue/blob/main/cloudbuild.yaml#L30
```release-note
NONE
```
=> use a bigger machine for cloud build

Makefile, site/content/en/docs/reference/leaderworkerset.v1.md
/kind cleanup
After https://github.com/kubernetes-sigs/lws/pull/428, there is no consistency between make generate-apiref and the code.
So, followed by https://github.com/kubernetes-sigs/kueue/blob/main/Makefile#L177 ,
Add more verification include:
- gomod
- fmt
- generate-apiref 
- generate
And fix the missed generated docs.
Fixes #484
```release-note
[CI] Add more verify include gomod, fmt, and generate-apiref 
```
=> [CI] Add more verify include gomod, fmt, and generate-apiref 

docs/examples/vllm/TPU/lws.yaml
Current multi-host TPU vLLM user guide doesn't work, need to update the directory where it is located
Fixes #
```release-note
```
=> [Docs] Fixed location of vLLM script on TPU image

charts/lws/README.md, site/content/en/docs/installation/_index.md
Add an example of using OCI to the Helm installation guide
Fixes #
Relate to https://github.com/kubernetes-sigs/lws/issues/499
```release-note
Add an example of using OCI to the Helm installation guide
```
=> Add an example of using OCI to the Helm installation guide

.github/ISSUE_TEMPLATE/NEW_RELEASE.md, Makefile, charts/lws/Chart.yaml, site/config.toml, site/content/en/docs/installation/_index.md
/kind cleanup
The PR includes:
* Add `prepare-release-branch` like kueue: https://github.com/kubernetes-sigs/kueue/blob/main/Makefile#L298, so it can use `make prepare-release-branch` to update versions automantically in the codebase.
* Add `prepare-release-branch` to the `make verify`, so it can be ensured by CI.
* Add the process to run `make prepare-release-branch` in  `.github/ISSUE_TEMPLATE/new-release.md`, like https://github.com/kubernetes-sigs/kueue/blob/main/.github/ISSUE_TEMPLATE/NEW_RELEASE.md
* Add helm OCI release process in  `.github/ISSUE_TEMPLATE/new-release.md`
* Run the  `make prepare-release-branch` to change to the versions in the code automatically
* Rename `new-release.md` to `NEW_RELEASE.md` for consistency.
Fixes #
```release-note
Add `prepare-release-branch` in …
```
=> Add `prepare-release-branch` in Makefile to update versions automatically

charts/lws/templates/manager/configmap.yaml
/kind bug
fix helm install fail by :
```
lws/templates/manager/configmap.yaml" at <.Values.certManager.enable>: nil pointer evaluating interface {}.enable
```
Fixes #
```release-note
NONE
```
=> Fix helm install panic by invalid values `.Values.certManager.enable`

site/content/en/docs/manage/cert_manager.md
Fixes # NA
```release-note
```
=> [doc] fix typo

keps/115-Subgroup-support/README.md
Since there're no detailed subgroup usage document so far ( I will contribute later )
so this KEP is the best place for people to learn about this feature, so fixing some confusions here.
Fixes #
```release-note
```
=> Doc: fix some typo in KEP 115 documents

site/content/en/docs/adoption/_index.md
/kind cleanup
Fixes #
```release-note
None
```
=> Add dynamo and new presentation

.github/ISSUE_TEMPLATE/NEW_RELEASE.md, Makefile, charts/lws/Chart.yaml, site/config.toml, site/content/en/docs/installation/_index.md
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/554
```release-note
```
=> Release v0.6.2

keps/552-worker-resizing/README.md, keps/552-worker-resizing/kep.yaml
/kind feature
/kind api-change
New KEP to allow updates to the `spec.leaderWorkerTemplate.size` field.
Fixes #552 
```release-note
```
=> KEP #552: allow updates to `spec.leaderWorkerTemplate.size` field

site/content/en/docs/adoption/_index.md
adding several talks and PPT for LWS
=> [talk and slides] adding KubeCon HK and JP 2025 talks for LWS

api/leaderworkerset/v1/leaderworkerset_types.go, charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
/kind feature
- Add Ready, Desired, Up-to-date columns for better visibility
- Users can now see replica status at a glance with `kubectl get lws`
```
NAME                     READY   DESIRED   UP-TO-DATE   AGE
leaderworkerset-sample   2       3         3            9m18s
```
Fixes #https://github.com/kubernetes-sigs/lws/issues/210
```release-note
NONE
```
=> feat: add meaningful printer columns to LeaderWorkerSet CRD

Makefile, charts/lws/Chart.yaml, charts/lws/values.yaml, site/config.toml, site/content/en/docs/installation/_index.md
According to the release.md, merge to the branch release-0.7.0
xref: https://github.com/kubernetes-sigs/lws/issues/595
/kind cleanup
Fixes #
```release-note
None
```
=> Release 0.7.0

Makefile, charts/lws/Chart.yaml, site/config.toml, site/content/en/docs/installation/_index.md
/kind cleanup
xref: https://github.com/kubernetes-sigs/lws/issues/607
Fixes #
```release-note
```
=> Release 0.6.3

pkg/controllers/leaderworkerset_controller.go
/kind style
Maintain a uniform `//+kubebuilder` style in the context. This is a relatively minor change, and more readable.
None
=> style: 🔨 Maintain a uniform +kubebuilder style in the context.

Dockerfile
/kind bug
Declare the variable `CGO_ENABLED` in Dockerfile.
=> fix: 🐛 Declare the variable CGO_ENABLED in Dockerfile

.github/workflows/codespell.yaml, api/leaderworkerset/scheme/scheme.go, docs/examples/llamacpp/tools/clichat/cmd/clichat/main.go, keps/173-headless-service-per-replica/README.md, keps/238-controller-revision/README.md, keps/257-Subgroup-leader-only/README.md, keps/511-partition-update/README.md, keps/552-worker-resizing/README.md, keps/622-volume-claim-templates/README.md, pkg/controllers/leaderworkerset_controller.go, pkg/controllers/pod_controller.go, pkg/utils/pod/pod_utils_test.go, site/content/en/docs/concepts/_index.md, site/content/en/docs/examples/llamacpp.md, site/layouts/shortcodes/include.html, test/e2e/e2e_test.go, test/integration/controllers/leaderworkerset_test.go, test/integration/webhooks/pod_test.go
**Reason for Change**:
test: add codespell github action
After this PR merged, there should be no mis-spelling any more
**Requirements**
**Issue Fixed**:
**Notes for Reviewers**:
=> test: add codespell github action
