pkg/controller/controller_utils.go, test/integration/controller/leaderworkerset_controller_test.go, test/testutils/validators.go
/kind bug
Fixes #
```release-note
None
```
=> Fix Available and Processing condition should not both be true 

Dockerfile, Makefile, cloudbuild.yaml
/kind cleanup
We missed a `cloudbuild.yaml`, together with some refactors to support this change.
See https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-lws-push-images/1765798132689408000:
```
Running...
$ARTIFACTS is set, sending logs to /logs/artifacts
[2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-lws-push-images/1765798132689408000#1:build-log.txt%3A2)024/0[3](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-lws-push-images/1765798132689408000#1:build-log.txt%3A3)/07 17:5[4](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-lws-push-images/1765798132689408000#1:build-log.txt%3A4):20 Build directory: .
2024/03/07 17:54:20 /home/prow/go/src/github.com/kubernetes-sigs/lws/cloudbuild.yaml does not exist
```
Fixes #
Use `make image-build` instead of …
=> Fix test-infra failed to build image

pkg/controllers/leaderworkerset_controller.go, pkg/controllers/pod_controller.go, pkg/webhooks/leaderworkerset_webhook.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go, test/testutils/wrappers.go
/kind cleanup
use package `k8s.io/utils/ptr` to replace the deprecated package`k8s.io/utils/pointer`.
Fixes #
```release-note
NONE
```
=> Cleanup deprecated package k8s.io/utils/pointer

pkg/controllers/leaderworkerset_controller.go, pkg/controllers/pod_controller.go, pkg/utils/accelerators/tpu.go, pkg/utils/accelerators/tpu_test.go, pkg/webhooks/pod_webhook.go, test/integration/webhooks/pod_test.go, test/testutils/util.go
/kind bug
LWS injects TPU env vars necessary for multi-host workloads, this includes TPU_WORKER_ID and TPU_HOST_NAMES. Currently we inject that into the workers if they request TPUs assuming that the leader does too, and so TPU_WORKER_ID=0 is always assumed to be the leader pod, and the leader hostname is also added to TPU_HOST_NAMES list. 
In some cases, the leader may not be requesting TPUs and is not acting as a TPU worker, in which case its hostname should not be listed in the host names and the TPU_WORKER_ID should be assigned to the LWS workers starting from 0 (and so TPU_WORKER_ID = LWS_WORKER_INDEX-1)
Fixes #
```release-note
```
=> Fix TPU env var assignment when leader doesn't request TPUs

Makefile, test/e2e/config/image_pull_policy.yaml, test/e2e/config/kustomization.yaml, test/e2e/e2e-test.sh, test/e2e/e2e_test.go, test/e2e/suite_test.go
/kind cleanup
Currently we lack any kind of E2E testing, added a test that starts a kind cluster with LWS controller and CRDs and assures LWS can be created.
Fixes https://github.com/kubernetes-sigs/lws/issues/6
Test change locally via `make test-e2e`
=> Add E2E test

Makefile, pkg/controllers/leaderworkerset_controller_test.go, test/e2e/e2e_test.go, test/testutils/util.go, test/testutils/validators.go, test/testutils/wrappers.go
/kind cleanup
Benefit to using existing kind cluster.
Fixes #
```release-note
None
```
=> Cleanup after e2e test

Makefile, api/leaderworkerset/v1/leaderworkerset_types.go, cmd/main.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, config/samples/leaderworkerset_v1_leaderworkerset.yaml, pkg/controllers/leaderworkerset_controller.go, pkg/controllers/leaderworkerset_controller_test.go, pkg/controllers/pod_controller.go, pkg/controllers/pod_controller_test.go, pkg/utils/pod/pod_utils.go, pkg/utils/statefulset/statefulset_utils.go, pkg/utils/utils.go, pkg/utils/utils_test.go, pkg/webhooks/leaderworkerset_webhook.go, pkg/webhooks/pod_webhook.go, test/e2e/e2e_test.go, test/integration/controllers/leaderworkerset_test.go, test/integration/controllers/suite_test.go, test/integration/webhooks/leaderworkerset_test.go, test/testutils/util.go, test/testutils/validators.go, test/testutils/wrappers.go
/kind feature
part of https://github.com/kubernetes-sigs/lws/issues/3
```release-note
Support maxUnavailable in rollout
```
=> Support maxUnavailable in rollout

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/controllers/leaderworkerset_controller.go, test/e2e/suite_test.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go, test/testutils/validators.go
/kind feature
part of https://github.com/kubernetes-sigs/lws/issues/3
```release-note
Add updatedReplicas to leaderWorkerSet status.
```
=> Add updatedReplicas to Status

client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go, hack/update-codegen.sh
/kind bug
Failed to run `make generate` when env variable `GOPATH` was not set.
```bash
root@dev:~/work/lws# make generate
test -s /root/work/lws/bin/controller-gen && /root/work/lws/bin/controller-gen --version | grep -q v0.14.0 || \
GOBIN=/root/work/lws/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
cp -f /root/go/pkg/mod/k8s.io/code-generator@v0.29.3/generate-groups.sh /root/work/lws/bin/
cp -f /root/go/pkg/mod/k8s.io/code-generator@v0.29.3/generate-internal-groups.sh /root/work/lws/bin/
cp -f /root/go/pkg/mod/k8s.io/code-generator@v0.29.3/kube_codegen.sh /root/work/lws/bin/
/root/work/lws/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
./hack/update-codegen.sh go /root/work/lws/bin
./hack/update-codegen.sh: line 26: GOPATH: unbound …
```
=> fix: make generate error: unbound variable

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/webhooks/leaderworkerset_webhook.go, pkg/webhooks/pod_webhook_test.go, test/integration/webhooks/leaderworkerset_test.go, test/testutils/wrappers.go
/kind cleanup
Fixes #15 
```release-note
NONE
```
=> cleanup: use kubebuilder marker instead of webhook

pkg/controllers/leaderworkerset_controller.go, pkg/webhooks/leaderworkerset_webhook.go, test/integration/controllers/leaderworkerset_test.go, test/integration/webhooks/leaderworkerset_test.go
/kind bug
With HPA enabled, the replicas could scale to zero, if we limit the maxUnavailable must less than replicas, it's impossible here.
Also add more strict policies to the validation.
Fixes #
```release-note
None
```
=> Fix maxUnavailable couldn't be bigger than replicas

pkg/controllers/leaderworkerset_controller.go, pkg/utils/constants/constants.go
/kind feature
- add event for lws controller 
I have only added an event recorder for the LWS controller and did not add any events for the pod controller. This decision was made because I believe that users will only be interested in events generated by the LWS controller and not those generated by the pod controller.
If there is a need to add events for the pod controller, please let me know and I will add them accordingly.
refer to: https://github.com/kubernetes-sigs/lws/issues/100
```release-note
None
```
=> feat: add event recorder event for lws controller

pkg/controllers/pod_controller.go
/kind cleanup
When lws not found, it's mostly because of deleted, if we do not tolerate the notFoundError here, we'll have plenty of 
unnecessary logs.
Fixes #
```release-note
None
```
=> Remove unnecessary notFoundError log

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/controllers/leaderworkerset_controller.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go
/kind bug
Fixes https://github.com/kubernetes-sigs/lws/issues/96#issuecomment-2063027769
```release-note
None
```
=> Change the semantics of leaderWorkerSet Replicas

pkg/utils/utils_test.go
/kind cleanup
Run unit tests using t.Errorf instead of t.Fatalf#### Which issue(s) this PR fixes
Fixes #
None
```release-note
None
```
=> use t.Errorf instead of t.Fatalf

pkg/controllers/leaderworkerset_controller.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/validators.go
/kind cleanup
Fixes #
```release-note
None
```
=> Simplify the partition update model

pkg/controllers/pod_controller.go
/kind bug
Fixes #
```release-note
```
=> fix: handle construct worker sts configuration error promptly

docs/example/vllm/README.md, docs/example/vllm/build/Dockerfile, docs/example/vllm/build/ray_init.sh, docs/example/vllm/lws.yaml, docs/example/vllm/service.yaml
add distributed vllm inference examples
Fixes #124
=> add vllm distributed inference examples

test/integration/controllers/leaderworkerset_test.go
/kind flake
/kind cleanup
/assign @liurupeng 
Fixes https://github.com/kubernetes-sigs/lws/issues/134
```release-note
None
```
=> Fix flaky test in maxSurge integration tests

Makefile
/kind cleanup
- Currently we support k8s versions: v1.27, v1.28, v1.29, so our e2e test image should be upgraded to v1.29.1
- kind version 0.18 -> 0.22
Fixes #
None
```release-note
```
=> chore: upgrade e2e kind version

api/leaderworkerset/v1/leaderworkerset_types.go, pkg/utils/accelerators/tpu.go, pkg/utils/pod/pod_utils.go, pkg/utils/pod/pod_utils_test.go, pkg/webhooks/pod_webhook.go, test/integration/webhooks/pod_test.go, test/testutils/util.go, test/testutils/wrappers.go
This adds LWS_LEADER_ADDRESS environment variable injection constructed via related LWS pod labels. This avoids making the user specify in yaml via downward api.
/kind feature
Fixes #143
```release-note
Add LWS_LEADER_ADDRESS environment variable to all containers in a leaderworkerset.
```
=> Add leader address environment variable injection

pkg/utils/pod/pod_utils.go, test/integration/webhooks/pod_test.go, test/testutils/util.go, test/testutils/wrappers.go
Quick change to make LWS_LEADER_ADDRESS to be the first container env var so we could reference that in the template from other env vars
Fixes #
```release-note
```
=> Switch the order of env var for LWS_LEADER_ADDRESS

.github/dependabot.yml
/kind cleanup
xref: https://github.com/kubernetes-sigs/lws/pull/154
wait for https://github.com/open-policy-agent/cert-controller/issues/207 to be fixed.
```release-note
None
```
=> Ignore controller-runtime upgrade

cmd/main.go, config/manager/manager.yaml
/kind feature
Fixes #19 
```release-note
```
=> add leader elect args

Makefile
Lint is failing on PRs.
Fixes #
```release-note
NONE
```
=> set golangci-lint for 15 minutes to be same as jobset

client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetspec.go
/kind cleanup
When construcitng lws obj, found missing the startupPolicy.
Fixes #
```release-note
None
```
=> Fix missing startupPolicy in applyConfiguration

docs/examples/vllm/README.md, docs/examples/vllm/build/Dockerfile, docs/examples/vllm/lws.yaml
Updates vLLM docs to show example of deploying Llama3-405B using LWS and Ray.
Fixes #184
```release-note
NONE
```
=> updating vllm docs to use llama3  405B as example

Makefile, pkg/controllers/leaderworkerset_controller.go, pkg/controllers/pod_controller.go, test/e2e/e2e_test.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go, test/testutils/validators.go, test/testutils/wrappers.go
/kind feature
Fixes https://github.com/kubernetes-sigs/lws/issues/189
```release-note
None
```
=> No worker sts when size=1

.golangci.yaml, pkg/utils/accelerators/tpu.go, pkg/utils/accelerators/tpu_test.go, pkg/webhooks/leaderworkerset_webhook.go
… for golangci-lint
/kind cleanup
Add golangci-lint configuration so people can add more lint packages over time.
I added unparam and fixed a few lint errors.
Fixes #193 
```release-note
NONE
```
=> add golangci config to project

api/leaderworkerset/v1/leaderworkerset_types.go, pkg/utils/pod/pod_utils.go, pkg/utils/pod/pod_utils_test.go, test/integration/webhooks/pod_test.go, test/testutils/util.go, test/testutils/wrappers.go
/kind feature
- Add group size environment variable injection
Fixes # https://github.com/kubernetes-sigs/lws/issues/203
```release-note
Add LWS_GROUP_SIZE environment variable to all containers in a leaderworkerset.
```
=> feature: Add group size environment variable injection

docs/examples/llamacpp/dev/tasks/load-images-into-docker, docs/examples/llamacpp/dev/tasks/stop-blobserver, docs/examples/llamacpp/docker-bake.hcl, docs/examples/llamacpp/images/bartowski/Dockerfile
/kind bug
- ` curl -v -L --fail -o Meta-Llama-3-8B-Instruct-Q5_K_M.gguf http://$(ip -4 route show default | awk '/default/ { print $3 }'):9999/16d824ee771e0e33b762bb3dc3232b972ac8dce4d2d449128fca5081962a1a9e; \` can not find the correct host IP when I run script on macOS
- the `--exact` option is unavailable on macOS
Test result:
```
(base) ➜  llamacpp git:(main) ✗ dev/tasks/run-in-kind
...
#23 [bartowski quantizer 5/6] RUN if [ -n "10.64.0.228" ]; then     curl -v -L --fail -o Meta-Llama-3-8B-Instruct-Q5_K_M.gguf http://10.64.0.228:9999/16d824ee771e0e33b762bb3dc3232b972ac8dce4d2d449128fca5081962a1a9e;   else     curl -v -L --fail -o Meta-Llama-3-8B-Instruct-Q5_K_M.gguf http://$(ip -4 route show default | awk '/default/ { print $3 …
```
=> Make llama.cpp example become avaliable on macOS

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/controllers/leaderworkerset_controller_test.go, pkg/controllers/pod_controller.go, pkg/webhooks/leaderworkerset_webhook.go, test/e2e/e2e_test.go, test/integration/controllers/leaderworkerset_test.go, test/integration/webhooks/leaderworkerset_test.go, test/testutils/wrappers.go
/kind feature
/kind cleanup
Fixes https://github.com/kubernetes-sigs/lws/issues/204
```release-note
Deprecated the DefaultRestartPolicy and replace with NoneRestartPolicy
```
=> Deprecated DefaultRestartPolicy with NoneRestartPolicy

pkg/utils/accelerators/tpu.go, pkg/utils/accelerators/tpu_test.go, test/testutils/util.go
/kind feature
When requesting TPU resources, it injects the environment variable TPU_NAMES, which contains the name of the pod the TPU is in. This is needed as popular distributed runtime libraries such as Ray expect this variable to be set https://github.com/ray-project/ray/blob/ab27fe805c3fef4c8dc66bf5804f32cd522d1aad/python/ray/_private/accelerators/tpu.py#L247
Fixes #
```release-note
NONE
```
=> Injecting TPU_NAME environment variable

pkg/controllers/pod_controller.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go
/kind bug 
Changes from patching the worker sts to update it, to create a new worker sts when it doesn't exist. The need for this change is described in https://github.com/kubernetes-sigs/lws/issues/225#issuecomment-2395473982 
Fixes #225 
```release-note
```
=> Creating new workerStatefulSet instead of patching when updating LWS template

keps/173-headless-service-per-replica/README.md
/kind cleanup
Fixes #228 
```release-note
```
=> Update KEP #173 to reflect implementation

pkg/utils/utils.go
/kind bug
When calculating the template hash, if the NetworkConfig has the defaulted value, it will not be used. This is to prevent a rolling update to be triggered when upgrading from a previous version.
Fixes #240 
```release-note
```
=> change to not use NetworkConfig in hash calculation if it has default value

api/leaderworkerset/v1/leaderworkerset_types.go, config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
/kind bug
The field subdomainPolicy doesn't have validation, causing unintended behavior if set to a value that isn't Shared or UniquePerReplica
Fixes #
```release-note
```
=> Added validation for subdomainPolicy values

pkg/utils/utils.go
Cherry pick of #250 on release-0.4.0.
#250: change to not use NetworkConfig in hash calculation if it has default value
```release-note
```
=> Automated cherry pick of #250: change to not use NetworkConfig in hash calculation if it has default value

cmd/main.go
This commit removes the separate leaderElectResourceNamespace flag and directly assigns the namespace flag value for leader election. This ensures consistency by using the same namespace for deployment and leader election, simplifying the configuration.
This commit removes the separate `leaderElectResourceNamespace` flag
and directly assigns the `namespace` flag value for leader election.
This ensures consistency by using the same namespace for deployment
and leader election, simplifying the configuration.
Fixes #262 
```release-note
```
=> Unify Leader Election Namespace with Deployment Namespace

cmd/main.go, config/default/manager_auth_proxy_patch.yaml, docs/setup/install.md, pkg/utils/utils.go
/kind feature
Users should not need to specify namespace in the deployment of the LWS operator. 
We want to default the namespace to where the serviceaccount of LWS lives. This allows us to avoid configuration problems where a user specifies the wrong namespace for the CLI and the deployment went to other namespace. In this case, the pod is non functional.
Fixes #
```release-note
If the namespace of leaderworkerset deployment is different from default, we will take the service account for the namespace.
```
=> Use the namespace of the service account

charts/lws/templates/manager/deployment.yaml
There is no `--namespace` flag on manager.
/kind bug
N/A
```release-note
NONE
```
=> Remove `namespace` arg from manager command

pkg/controllers/leaderworkerset_controller.go, pkg/utils/revision/revision_utils.go, pkg/utils/revision/revision_utils_test.go, test/integration/controllers/leaderworkerset_test.go, test/testutils/util.go, test/testutils/validators.go
/kind cleanup
Adds tests for Controller Revision
Fixes #294
```release-note
```
=> Tests for Controller Revision

pkg/controllers/leaderworkerset_controller.go
Minimize the number of unnecessary logs that get emitted
Fixes #
```release-note
```
=> Minimize number of unnecessary logs

api/leaderworkerset/v1/leaderworkerset_types.go, cmd/main.go, pkg/controllers/leaderworkerset_controller.go, pkg/controllers/leaderworkerset_controller_test.go, pkg/controllers/pod_controller.go, test/integration/controllers/leaderworkerset_test.go, test/integration/controllers/suite_test.go, test/testutils/validators.go
/kind feature
Adds more events 
Fixes #243 
```release-note
```
=> Add Events

pkg/controllers/pod_controller.go
/kind cleanup
Returns gracefully if the leaderPod is not found when handling a worker pod. 
This happens when a rolling update is occurring. The leaderPod gets deleted, which triggers the worker pods to be deleted. Since the leader has already been deleted, the Get Operation will fail, but this is intended behavior.
Fixes #
```release-note
```
=> Ignore not found error when handling ReacreateGroupOnPodRestart

charts/lws/templates/manager/deployment.yaml, charts/lws/templates/manager/service.yaml
/kind cleanup
As part of #274, need to remove the container from the helm charts
Fixes #
```release-note
```
=> Removed kube-rbac-proxy container from helm charts

pkg/controllers/leaderworkerset_controller_test.go, pkg/controllers/pod_controller_test.go, pkg/utils/accelerators/tpu_test.go, pkg/utils/pod/pod_utils_test.go, pkg/utils/revision/revision_utils_test.go, test/e2e/e2e_test.go, test/e2e/suite_test.go, test/integration/controllers/leaderworkerset_test.go, test/integration/webhooks/leaderworkerset_test.go, test/integration/webhooks/pod_test.go, test/wrappers/wrappers.go
/kind cleanup
Fixes #296
```release-note
```
=> Refactored wrappers into its own package

keps/238-controller-revision/README.md
=> Update KEP #238 to reflect implementation

charts/lws/templates/rbac/clusterrole.yaml
/kind bug
helm chart lacks rbac about `controllerrevisions`
```
W0115 07:24:15.739964       1 reflector.go:561] pkg/mod/k8s.io/client-go@v0.31.4/tools/cache/reflector.go:243: failed to list *v1.ControllerRevision: controllerrevisions.apps is forbidden: User "system:serviceaccount:lws-system:lws-controller-manager" cannot list resource "controllerrevisions" in API group "apps" at the cluster scope
E0115 07:24:15.740000       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.4/tools/cache/reflector.go:243: Failed to watch *v1.ControllerRevision: failed to list *v1.ControllerRevision: controllerrevisions.apps is forbidden: User \"system:serviceaccount:lws-system:lws-controller-manager\" cannot list resource \"controllerrevisions\" in API group \"apps\" at the cluster …
```
=> Add controllerrevisions rbac to helm chart.

Dockerfile, Makefile
/kind feature
I modified Makefile and Dockerfile so that we can provide the multi-platform supported container image.
Fixes #275
```release-note
Make lws image multi-platform
```
=> Make lws image multi-platform

pkg/controllers/pod_controller.go
/kind cleanup
This log is redundant, as the event here https://github.com/kubernetes-sigs/lws/blob/78998a045cc582a21a6fb75600c90d24178d86d4/pkg/controllers/pod_controller.go#L212 already describes that a Pod group restart was triggered. It can also spam the logs in the case of a large pod group.
Fixes #337 
```release-note
```
=> Removed restarting group log in pod controller

pkg/controllers/pod_controller.go
Cherry pick of #342 on release-0.5.1.
#342: Added handling of nil revision in pod controller
```release-note
```
=> Automated cherry pick of #342: Added handling of nil revision in pod controller

charts/lws/templates/webhook/webhook.yaml, config/webhook/manifests.yaml, pkg/webhooks/pod_webhook.go
Cherry pick of #347 on release-0.5.1.
#347: Removed update operation from pod webhook
```release-note
```
=> Automated cherry pick of #347: Removed update operation from pod webhook

pkg/controllers/pod_controller.go
Cherry pick of #341 on release-0.5.1.
#341: Removed restarting group log in pod controller
```release-note
```
=> Automated cherry pick of #341: Removed restarting group log in pod controller

Makefile, cmd/main.go, cmd/main_test.go, pkg/controllers/leaderworkerset_controller.go, pkg/webhooks/leaderworkerset_webhook.go
/kind cleanup
It was suggested in here https://github.com/kubernetes-sigs/lws/pull/325#discussion_r1923006469 by @kerthcet to deprecate the flags, because passing them in the configuration file via `--config` flag is cleaner.
This PR
* Deprecates the flags as continuation of https://github.com/kubernetes-sigs/lws/pull/325
* Migrates from deprecated function `GetValueFromIntOrPercent` to `GetScaledValueFromIntOrPercent`
* Moves metric server initialization logic in `apply` function as suggested in https://github.com/kubernetes-sigs/lws/pull/325#discussion_r1926762256
Fixes #
```release-note
Deprecating the flags whose can be cleanly passed through configuration file
```
=> Deprecate flags as the recommended path is to pass configuration file

Makefile, Makefile-deps.mk
/kind cleanup
Code base relies on 1.32 of k8s. But the dependencies in Makefiles point to older versions. 
This PR updates;
* `ENVTEST_K8S_VERSION` to 1.32.0
* Kind image tag to 1.32.0
* kind go module to 0.26
* golangci-lint to 1.63.4
Fixes #
```release-note
None
```
=> Update k8s binary dependencies to align with 1.32

client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go, hack/update-codegen.sh
/kind bug
/kind api-change
This PR adds the external types the LWS API depends on to the code-generator command so the generated client apply configurations are complete and do not rely on "non-apply" types.
```release-note
Add missing external types to apply configurations
```
=> Add missing external types to apply configurations

cmd/main_test.go
/kind bug
`LeaderElectionNamespace` is set by the namespace of the running pod, so that it is naturally dynamic. Running cmd/main_test.go on live clusters fails with the mismatch of `LeaderElectionNamespace`. 
This PR ignores this field in cmd/main_test.go executions.
Fixes #
```release-note
None
```
=> Ignore LeaderElectionNamespace in cmd unit tests as it is dynamic

Makefile
/kind cleanup
There are go.mods under `docs/examples/llamacpp/tools/` path (e.g. `docs/examples/llamacpp/tools/blobserver/go.mod`) which are not directly related to the actual code block and they present only as an examples. However, controller-gen executes also for them unnecessarily. 
This PR modifies controller-gen's path to only execute `api` and `pkg` to align with jobset https://github.com/kubernetes-sigs/jobset/blob/e8702b95e33c38d8a856ab63b14ffec5abd5e22a/Makefile#L90
Additionally, this PR updates to use branch name instead of commit hash in setupenv-test binary for better readability.
```release-note
None
```
=> Run controller-gen only for api and pkg directories

api/leaderworkerset/v1/leaderworkerset_types.go, pkg/utils/pod/pod_utils.go, pkg/utils/pod/pod_utils_test.go, test/testutils/util.go, test/wrappers/wrappers.go
When using sglang for distributed inference, it is necessary to use the environment variable LWS_WORKER_INDEX, which can be directly injected and used
Fixes #
```release-note
```
=> Inject environment variable LWS_WORKER_INDEX

pkg/utils/controller/controller_utils.go
/kind feature
From the comment in https://github.com/kubernetes-sigs/lws/blob/main/api/leaderworkerset/v1/leaderworkerset_types.go#L35 ,  
The service needs to have the label `leaderworkerset.sigs.k8s.io/name`.
Add Label `leaderworkerset.sigs.k8s.io/name` to the headlessService.
Needs to change the docs after https://github.com/kubernetes-sigs/lws/pull/431 merged.
Fixes #429
```release-note
Add Label `leaderworkerset.sigs.k8s.io/name` to the headlessService.
```
=> Add Label `leaderworkerset.sigs.k8s.io/name` to the headlessService

api/leaderworkerset/v1/leaderworkerset_types.go
…sigs.k8s.io/subgroup-size`
/kind cleanup
From the KEP: https://github.com/kubernetes-sigs/lws/blob/main/keps/115-Subgroup-support/README.md?plain=1#L144,
the annotation needs to be `leaderworkerset.sigs.k8s.io/subgroup-size`, 
So change annotation `leaderworkerset.gke.io/subgroup-size` to `leaderworkerset.sigs.k8s.io/subgroup-size`.
And needs to change the docs if https://github.com/kubernetes-sigs/lws/pull/431 is merged.
The label should be more consistent with others.
Fixes #430
```release-note
Change annotation  `leaderworkerset.gke.io/subgroup-size` to `leaderworkerset.sigs.k8s.io/subgroup-size`
```
=> Change annotation `leaderworkerset.gke.io/subgroup-size` to `leaderworkerset.sigs.k8s.io/subgroup-size`

config/samples/leaderworkerset_exclusiveplacement.yaml, config/samples/leaderworkerset_multi_template.yaml, config/samples/leaderworkerset_tpu.yaml, config/samples/leaderworkerset_v1_leaderworkerset.yaml, docs/examples/sample/lws-exclusive-placement.yaml, docs/examples/sample/lws-multi-template.yaml, docs/examples/sample/lws-restart-policy.yaml, docs/examples/sample/lws-rollout-strategy.yaml, docs/examples/sample/lws.yaml, pkg/controllers/leaderworkerset_controller_test.go, pkg/controllers/pod_controller_test.go, site/content/en/docs/concepts/_index.md, test/e2e/e2e_test.go, test/integration/controllers/leaderworkerset_test.go, test/wrappers/wrappers.go
/kind cleanup
curl-metrics test tries to run a curl command to collect the metrics and
it is intended to be short lived. This is typical use case for jobs rather
than pods. This PR modifies the test to run job by using `kubectl create job`
command. Besides, kubectl run is not recommended.
Additionally, Default nginx image requires privileged access in the pod which is
unwanted and not recommended even in testing environments.
This PR switches to `nginxinc/nginx-unprivileged` that installs nginx
in an unprivileged way. This PR also updates the nginx version to 1.27
instead of the very old 1.14.2 (we only need to update the e2e tests, but just to
align all the pieces, this PR switches everywhere to the same version).
This PR must no affect on any functionality or any test.
```release-note …
```
=> Use create jobs command instead of run pods in e2e testing

charts/lws/values.yaml, config/manager/manager.yaml
/kind cleanup
This PR sets `readOnlyRootFilesystem` to true. This is important aspect to prevent any writes in root file system. Besides, LWS does not need to write root file system at all.
```release-note
Setting the pods readOnlyRootFilesystem to true
```
=> Set readOnlyRootFilesystem explicitly to true

charts/lws/templates/manager/deployment.yaml, charts/lws/templates/manager/service.yaml, config/default/kustomization.yaml, config/default/manager_metrics_patch.yaml
/kind cleanup
Although metrics should serve without mentioning this explicitly in deployment yaml (as we discussed in https://github.com/kubernetes-sigs/jobset/pull/844#issuecomment-2742642125), this is a good UI to define this port in deployment spec.
```release-note
Adding 8443 metrics port in deployment's containerPort field
```
=> Explicitly bind metrics 8443 as containerPort in kustomize and helm

Makefile
/kind cleanup
Changes envtest to use latest instead of pinned version. Overall, it is better to update the go version if issues arise, over having to update the envtest library tag. Similar discussion on the JobSet side: https://github.com/kubernetes-sigs/jobset/pull/841/files#r2003165645
Fixes #
```release-note
```
=> Update envtest to use latest

pkg/webhooks/leaderworkerset_webhook.go, test/integration/webhooks/leaderworkerset_test.go
/kind bug
Scale to 0 is not worked when rolling update is enabled. Skip the related check should be considered.
Fixes #
```release-note
```
=> ignore 0 replica check

docs/examples/sglang/lws.yaml, site/content/en/docs/reference/labels-annotations-and-environment-variables.md
/kind cleanup
Remove the use of Downward API for `LWS_WORKER_INDEX` since it's injected by LWS automatically since v0.6.0.
Fixes #427
```release-note
docs: remove the use of Downward API for LWS_WORKER_INDEX
```
=> docs: remove the use of Downward API for LWS_WORKER_INDEX

site/content/en/docs/installation/_index.md
/kind cleanup
We restructured the helm charts path before releasing v0.6.0 in k8s-infra, see kueue  for example: https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-kueue/images.yaml#L1. For lws, we have to release another version like v0.6.1, then we can access the helm chart via commands like `helm push artifacts/lws-chart-v0.6.1.tgz oci://us-central1-docker.pkg.dev/k8s-staging-images/lws/charts`. However, I'm not going to release another version  since we just published one, and people can actually access the helm chart via our release page, see https://github.com/kubernetes-sigs/lws/releases/tag/v0.6.0. 
Let's make it happen at next release and we can see that the helm chart is pushed successfully here: …
=> Update helm install documentation

pkg/controllers/leaderworkerset_controller.go, test/integration/controllers/leaderworkerset_test.go
/kind bug
**Fixes #400**  
**Bug Scenario**:  
A condition occurs where the LWS worker StatefulSet has not yet been properly initialized.  
**Root Cause**:  
In  https://github.com/kubernetes-sigs/lws/pull/298/files#diff-636763c4aab72861dbe05856e71e11abf551830d79fdcd848f3133ffc9c2d6e1R386 , the introduction of the `continue` keyword causes `currentNonBurstWorkerCount++` to execute prematurely.  
This leads to the condition `updatedNonBurstWorkerCount < currentNonBurstWorkerCount` at https://github.com/kubernetes-sigs/lws/blob/v0.6.0/pkg/controllers/leaderworkerset_controller.go#L441 , triggering the bug.  
**Fix**:  
Simply move `currentNonBurstWorkerCount++` **below** the `continue` statement to resolve the issue.  
```release-note
Fix UpdateInProgress conditions for newly created LWS …
```
=> Fix UpdateInProgress conditions for newly created LWS

charts/lws/templates/certmanager/certificate.yaml, charts/lws/templates/certmanager/certificatemetrics.yaml, charts/lws/templates/manager/deployment.yaml, charts/lws/templates/prometheus/monitor.yaml, config/certmanager/certificate-metrics.yaml, config/certmanager/certificate.yaml, config/certmanager/kustomization.yaml, config/components/prometheus/kustomization.yaml, config/components/prometheus/monitor_tls_patch.yaml, config/default/cert_metrics_manager_patch.yaml, config/default/kustomization.yaml
/kind feature
ServiceMonitor resource is configured to serve TLS with `insecureSkipVerify: true` . However, this is not recommended for production use cases. This PR injects the appropriate certificates to the ServiceMonitor to serve from the trusted certificates within the cluster, when cert-manager (or another external certificate management tool) is enabled.
This PR configures kustomize and helm charts according to this. 
There is no functional change, when internal cert management is enabled (which is the default setting).
This PR is inspired by https://github.com/kubernetes-sigs/kueue/pull/4385
```release-note
Injecting certificates to ServiceMonitor in order to serve securely, when cert-manager is enabled
```
=> Inject certs for metrics endpoint when cert-manager is enabled

charts/lws/templates/manager/configmap.yaml, charts/lws/templates/manager/deployment.yaml, config/manager/controller_manager_config.yaml
/kind bug
Helm chart does not support configuring LWS configuration like Kustomize. This PR defines this configuration as configmap and binds it to deployment as a volume to be used by the application. 
Fixes https://github.com/kubernetes-sigs/lws/issues/514
```release-note
None
```
=> Add LWS configuration in Helm Charts

Makefile, hack/e2e-test.sh, test/e2e/config/certmanager/image_pull_policy.yaml, test/e2e/config/certmanager/kustomization.yaml
/kind cleanup
Currently e2e testing only runs against one setup configuration (i.e. internal cert manager is enabled). This puts us on a risk that changes may accidentally break the other type of configurations, such as cert-manager is installed. We need to increase our coverage for a better maintenance. 
As we discussed in https://github.com/kubernetes-sigs/lws/pull/478#issuecomment-2833260242, this PR adds a new Makefile target as `test-e2e-cert-manager` and this target will be run as a new CI job by executing the exact same e2e tests. This new target enables cert-manager and other required configurations in **Kustomize** and expect no test failure.
In the future, we'll definitely need a similar one specific to Helm installation.
```release-note
None
```
=> Run e2e tests also when cert-manager is enabled

charts/lws/templates/manager/configmap.yaml
/kind bug
There is an incorrect config name which is actually for JobSet not LWS. This PR updates it to LWS config api group.
```release-note
None
```
=> Use correct lws apigroup name

pkg/controllers/leaderworkerset_controller.go, test/integration/controllers/leaderworkerset_test.go
/kind bug
The bug is as follows:
* assume replicas readiness is [NOT_READY, READY]
* update is triggered, with MaxUnavailable=1
* update starts updating the replica-1, causing complete downtime, while the desired behavior would be to wait for replica-0 to become ready
The replica-0 might be unavailable for a variety of reasons like hardware issues, node patching etc.
The fix is to reduce partition less aggressively - taking into account pods that are not ready.
Note that the fix was tested on a cluster with MaxUnavailableStatefulSet feature disabled (I don't have access to a cluster with this feature enabled, maybe the issue is less impactful there, however arguably still beneficial since the lws considers readiness of leader+workers and not only leader).
I have not created a dedicated …
=> Fix issue with rolling update when some existing replicas are unhealthy

charts/lws/templates/webhook/service.yaml
/kind bug
FYI: https://llmaz.inftyai.com/docs/getting-started/installation/
```
(base) ➜  llmaz git:(main) kubectl -n llmaz-system  get ep
NAME                                       ENDPOINTS                                                          AGE
ai-gateway-controller                      10.244.0.16:9090,10.244.0.16:1063                                  62s
envoy-gateway                              10.244.0.15:18000,10.244.0.15:18001,10.244.0.15:9443 + 2 more...   62s
llmaz-controller-manager-metrics-service   10.244.0.17:8443                                                   62s
llmaz-webhook-service                      10.244.0.17:9443                                                   62s
lws-webhook-service                        10.244.0.14:9443,10.244.0.17:9443 …
```
=> Fix lws chart: the webhook service selects unexpected pods when it is  introduced as a dependency

charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml, pkg/webhooks/leaderworkerset_webhook.go
/kind bug
1) check optional field not nil which may come from older CRD
2) modify the CRD file in charts sub-folder ( copy that part from `config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml` generated by `make artifacts`)
NOTE: the "charts/" folder seems being manually maintained,  I cannot directly override the files under `charts` folder , with kustomize generated `config/`  files.
Fixes #529 
```release-note
```
=> fix: check optional field not nil before reference

pkg/controllers/leaderworkerset_controller.go, test/e2e/e2e_test.go, test/testutils/util.go, test/testutils/validators.go
/kind bug
Fixes
The deletion will fall into infinite loop with command `kubectl delete lws --cascade='foreground'`.
Simple e2e test appended.
```release-note
```
=> fix: support foreground deletion

charts/lws/templates/webhook/service.yaml
Cherry pick of #536 on release-0.6.0.
#536: Fix lws chart: the webhook service selects unexpected pods when it is  introduced as a dependency
```release-note
Fix lws chart: the webhook service selects unexpected pods when it is  introduced as a dependency
```
=> Automated cherry pick of #536: Fix lws chart: the webhook service selects unexpected pods when it is  introduced as a dependency

pkg/controllers/leaderworkerset_controller.go, test/e2e/e2e_test.go, test/testutils/util.go, test/wrappers/wrappers.go
/kind bug
fix rolling update stuck that when old pods were not ready
Fixes #567 
```release-note
```
=> fix rolling update stuck that when old pods were not ready

hack/update-codegen.sh
/kind cleanup
The  https://github.com/kubernetes/code-generator/issues/165 has been resolved in  v0.30.0
Removes the unneeded workaround from the hack/update-codegen.sh script , like kueue at: https://github.com/kubernetes-sigs/kueue/commit/c03277c969f4682cdaf119a2133664d9e76b95db#diff-149dfe7bb29d1191dceae3a52915e750e64b7f87257a5fb309c29d3056e2a95dL30
Fixes #
```release-note
NONE
```
=> Remove workaround for code-generator

hack/update-codegen.sh, site/content/en/docs/concepts/failure-handling/_index.md
This PR adds new documentation for LeaderWorkerSet's failure handling and restart policies to help users understand how LWS manages pod failures and node outages.
Fixes #586
```release-note
NONE
```
=> docs: Add failure handling and restart policies documentation

pkg/webhooks/leaderworkerset_webhook.go
/kind bug
With this PR https://github.com/kubernetes-sigs/lws/pull/563, new `Partition` field is defined in `RollingUpdateConfiguration`. However, controller assumes that this field is non-empty which consequently leads to a panic.
This PR defaults Partition field in RollingUpdateConfiguration to 0 as defined in the spec https://github.com/kubernetes-sigs/lws/blob/af5d4295972e4647acbd2da8c4b2be7080893d24/api/leaderworkerset/v1/leaderworkerset_types.go#L277
Fixes https://github.com/kubernetes-sigs/lws/issues/593
```release-note
None
```
=> Default Partition in RollingUpdateConfiguration to 0 to align with spec

Makefile, charts/lws/values.yaml, config/manager/kustomization.yaml
fix: https://github.com/kubernetes-sigs/lws/issues/596
Only happened in branch: release-0.6.0
/kind bug
Fixes #
After running:
- make artifacts IMAGE_REGISTRY=registry.k8s.io/lws GIT_TAG=0.6.3
- ./bin/helm template lws ./artifacts/lws-chart-0.6.3.tgz | grep -A 50 "kind: Deployment"
Get the result:
```yaml
spec:
replicas: 1
selector:
matchLabels:
control-plane: controller-manager
app.kubernetes.io/name: lws
app.kubernetes.io/instance: lws
template:
metadata:
labels:
control-plane: controller-manager
app.kubernetes.io/name: lws
app.kubernetes.io/instance: lws
spec:
serviceAccountName: lws-controller-manager
securityContext:
runAsNonRoot: true
terminationGracePeriodSeconds: 10
containers:
- args:
- --leader-elect
- --zap-log-level=2
command:
- /manager
name: manager
securityContext: …
```
=> Fix: use the main image in helm chart

docs/examples/llamacpp/dev/tasks/run-in-kind
/kind bug
When llm endpoint port is 80, met issues:
```
[wewang@ llamacpp]$ oc  run clichat --image=quay.io/wewang58/clichat:latest  --rm=true -it --image-pull-policy=IfNotPresent --env=LLM_ENDPOINT=http://llamacpp:80 --env=DEBUG=true
If you don't see a command prompt, try pressing enter.
generating with llama.cpp: making HTTP request: Post "http://llamacpp:80/completion": dial tcp 10.xx.xx.xxx:80: connect: connection refused
Session ended, resume using 'oc attach clichat -c clichat -i -t' command when the pod is running
pod "clichat" deleted
```
After update port to 8080, the endpoint can be visited:
```
[wewang@ llamacpp]$ oc  run clichat --image=quay.io/wewang58/clichat:latest  --rm=true -it --image-pull-policy=IfNotPresent --env=LLM_ENDPOINT=http://llamacpp:8080 --env=DEBUG=true
If …
```
=> fix: LLM endpoint port update

Makefile, cmd/main.go, pkg/version/version.go
/kind cleanup
chore: add buildDate in driver init logs
this would be easier for troubleshooting especially in local testing
```
2025-09-09T13:18:46Z    INFO    setup   Initializing    {"gitVersion": "v0.6.1-65-geedb14a-dirty", "buildDate": "2025-09-09T13:15:18Z", "gitCommit": "eedb14a617651fbdf3c3db90c71acc079dded959", "userAgent": "lws/v0.6.1-65-geedb14a-dirty (linux/amd64) eedb14a"}
```
Fixes #
```release-note
none
```
=> chore: add buildDate in driver init logs

cmd/main.go
/kind cleanup
chore: add version parameter, that would be easier for debug
```
Version: v0.6.1-74-g5e3a85a-dirty
Build Date: 2025-09-15T14:27:25Z
Git Commit: 5e3a85ae393d2daac4f8dc247b98e684c7178d8b
~/go/src/sigs.k8s.io/lws# echo $?
0
```
Fixes #
```release-note
none
```
=> chore: add version parameter

site/content/en/docs/adoption/_index.md
This PR adds Red Hat into adopters section in https://lws.sigs.k8s.io/docs/adoption/, as lws-operator (github.com/openshift/lws-operator) has been released. 
```release-note
None
```
=> Add Red Hat in adopters

site/content/en/docs/concepts/_index.md
What type of PR is this?
What this PR does
Expands the SubGroup section in the Concepts docs:
Added explanation of subgroup size
Documented the LeaderOnly subgroup type
Linked to [KEP-257](https://github.com/kubernetes-sigs/lws/blob/main/keps/257-Subgroup-leader-only/README.md) for more details
Why this is needed
Clarifies how SubGroups work and introduces LeaderOnly for users of distributed/HPC workloads.
Closes https://github.com/kubernetes-sigs/lws/issues/654
=> docs: expand SubGroup section with size and LeaderOnly type
